PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX schema: <http://schema.org/>
PREFIX schema2: <https://schema.org/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX exm: <http://example.org/movie/>
PREFIX ex: <http://example.org/>

# Requête pour trouver le pays avec le plus de victoires en 2018, son pilote ayant le plus de victoires, et les films oscarisés et Netflix
SELECT ?nameCountry ?winCount ?pilotName ?movieTitle ?maxMovie ?netflixMovieCount
WHERE {
  #Calcul du pays ayant le plus de victoires en 2018 et sélection du pilote avec le maximum de victoires pour ce pays
  {
    SELECT ?nameCountry ?pilotName (COUNT(?match) AS ?winCount)
    WHERE {
      ?match dbo:date ?date .
      FILTER(?date >= "2018-01-01" && ?date <= "2018-12-31")

      {
        ?match ex:homeTeamResult "Win";
               ex:hasHomeTeam ?team .
        ?team dbo:country ?country ;
              schema:name ?nameCountry .
      }
      UNION
      {
        ?match ex:homeTeamResult "Lose";
               ex:hasAwayTeam ?team .
        ?team dbo:country ?country ;
              schema:name ?nameCountry .
      }
      
      # Sélection du pilote avec le maximum de victoires pour le pays
      SERVICE <http://127.0.0.1:3030/formula/query> {
        ?p a foaf:Person ;
           schema2:countryOfOrigin ?nameCountry ;
           dbo:wins ?wins ;
           foaf:name ?pilotName .
      }
    }
    GROUP BY ?nameCountry ?pilotName
    ORDER BY DESC(?winCount) DESC(?wins)
    LIMIT 1
  }
  
  #Compter les films oscarisés et les films Netflix pour ce pays
  {
    SELECT (COUNT(?movie) AS ?maxMovie) (COUNT(?netflixMovie) AS ?netflixMovieCount)
    WHERE {
      SERVICE <http://127.0.0.1:3030/oscar/query> {
        ?movie a dbo:Movie ;
               dbo:country ?nameCountry ;
               exm:winner "Yes" ;
               schema:name ?movieTitle .
      }
      OPTIONAL {
        SERVICE <http://127.0.0.1:3030/netflix/query> {
          ?netflixMovie a schema:Movie ;
                         schema:name ?movieTitle .
        }
      }
    }
  }
}
LIMIT 1
